apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: rust-test
  namespace: axyomcore-portal
  labels:
    5g-core.casa-systems.com/taskType: unit-test
    app.kubernetes.io/component: tekton-task
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/part-of: axyomcore-portal
    app: axyom-backstage-provider-tekton
    app.kubernetes.io/name: axyom-backstage-provider-tekton
  annotations:
    tekton.dev/tags: rust-test
    tekton.dev/displayName: "cargo test"
spec:
  steps:
  - image: docker.artifactory.casa-systems.com/rust:1.81.0
    name: cargo-test
    computeResources:
      requests:
        memory: 1Gi
        cpu: 100m
      limits:
        memory: 2Gi
        cpu: 200m
    script: |
      git config --global --add safe.directory $(workspaces.source.path)
      cd $(workspaces.source.path)
      echo "Path: $(workspaces.source.path)"

      cargo test

      chown -R root:root .
    workingDir: $(workspaces.source.path)
  workspaces:
  - name: source
