apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: axyom-backstage-provider-push
  labels:
    app: axyom-backstage-provider-tekton
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: axyom-backstage-provider-tekton
    app.kubernetes.io/part-of: axyomcore-portal
spec:
  params:
    - name: repo-url
      type: string
    - name: sslVerify
      type: string
      description: Skip git SSL cert verification. Default true.
      default: false
    - name: sslSkipKanikoVerify
      type: string
      default: true
    - name: image-registry
      type: string
    - name: image-tag
      type: string
    - name: release-name
      type: string
    - name: git-revision
      type: string
    - name: kanikoVerbosity
      type: string
      default: debug
    - name: git-event-name
      description: GitLab WebHook name used in Pipelines to filter tasks
  workspaces:
    - name: shared-data
    - name: docker-credentials
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
      params:
        - name: url
          value: $(params.repo-url)
        - name: sslVerify
          value: $(params.sslVerify)
        - name: revision
          value: $(params.git-revision)
    - name: rust-test
      when:
        - input: $(params.git-event-name)
          operator: in
          values: ["push"]
      runAfter: ["fetch-source"]
      taskRef:
        name: rust-test
      workspaces:
        - name: source
          workspace: shared-data
    - name: rust-build
      when:
        - input: $(params.git-event-name)
          operator: in
          values: ["push"]
      runAfter: ["rust-test"]
      taskRef:
        name: rust-build
      workspaces:
        - name: source
          workspace: shared-data
    - name: kaniko
      when:
        - input: $(params.git-event-name)
          operator: in
          values: ["release", "tag-push"]
      runAfter: ["fetch-source"]
      taskRef:
        name: kaniko
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: docker-credentials
      params:
        - name: DOCKERFILE
          value: $(workspaces.source.path)/docker/Dockerfile.kaniko
        - name: EXTRA_ARGS
          value:
            - --skip-tls-verify=$(params.sslSkipKanikoVerify)
            - --verbosity=$(params.kanikoVerbosity)
            - --cache=false
            - --destination=$(params.image-registry):latest
        - name: IMAGE
          value: $(params.image-registry):$(params.image-tag)
    - name: deploy
      when:
        - input: $(params.git-event-name)
          operator: in
          values: ["release", "tag-push"]
      runAfter: ["kaniko"]
      taskRef:
        name: kpt-deploy
      workspaces:
        - name: source
          workspace: shared-data
      params:
        - name: path
          value: deploy/kpt/prod/axyom-backstage-provider
        - name: output
          value: table
