apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: axyom-backstage-provider-push
  labels:
    app: axyom-backstage-provider-tekton
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: axyom-backstage-provider-tekton
    app.kubernetes.io/part-of: axyomcore-portal
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "gitlab"
      params:
        - name: "secretRef"
          value:
            secretName: gitlab-axyom-backstage-provider-secret
            secretKey: secretToken
        - name: "eventTypes"
          value:
            - "Tag Push Hook"
            - "Push Hook"
    - ref:
        name: cel
      params:
        - name: filter
          value: "body.event_name.endsWith(\"push\") \n"
        - name: "overlays"
          value:
            - key: git-tag
              expression: "body.ref.split('/')[2]"
            - key: git-revision
              expression: "body.checkout_sha"
            - key: git-short-sha
              expression: "body.checkout_sha.truncate(7)"
            - key: git-event-name
              expression: "body.event_name.replace('_','-')"
  bindings:
    - ref: axyom-backstage-provider-push
  template:
    ref: axyom-backstage-provider-push
