# k8s cluster name
name: k8s-entity-provider
display: example Backstage Entity Provider
cluster: apple

server:
  port: 8000
  host: 0.0.0.0
  cors:
    enabled: true
    # allowed_origins: ["*"]
    allow_all_origins: true
    allow_methods: "GET, POST, PUT, DELETE, OPTIONS"
    allow_headers: "Content-Type, Authorization"
    allow_credentials: true
    max_age: 3600
  rate_limit:
    enabled: true
    max_requests: 2000
    window_seconds: 60
    requests_per_second: 100
    burst_size: 200
  
backstage:
  name: example-portal
  # Backstage annotations requied to make Entities visible in the Catalog.  
  annotations:
    backstage.io/managed-by-location: "url: http://acme-backstage-provider.example-portal.svc/api/v1/entities"
    backstage.io/managed-by-origin-location: "url: http://acme-backstage-provider.example-portal.svc/api/v1/entities"
  groups: {}

nats:
  # proxy_url: http://localhost:9080
  proxy_url: http://localhost:8080/api/v1/event

cache:
  def_channel_size: 32
  poll_interval: 30
  purge_cache_interval: 45
  
kube:
  use_tls: false
  resources: []
