apiVersion: v1
kind: ServiceAccount
metadata:
  name: acme-backstage-provider
  labels:
    app: acme-backstage-provider
    app.kubernetes.io/component: entity-provider
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: acme-backstage-provider
    app.kubernetes.io/part-of: acme-portal
  namespace: acme-portal
