apiVersion: v1
kind: Service
metadata:
  name: acme-backstage-provider
  labels:
    app: acme-backstage-provider
    app.kubernetes.io/component: entity-provider
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/name: acme-backstage-provider
    app.kubernetes.io/part-of: acme-portal
  namespace: acme-portal
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: acme-backstage-provider
    app: acme-backstage-provider
    app.kubernetes.io/component: entity-provider
    app.kubernetes.io/managed-by: kpt
    app.kubernetes.io/part-of: acme-portal
  sessionAffinity: None
  type: ClusterIP
